"""모든 LLM Provider가 따르는 공통 Adapter 계약입니다."""

from typing import Any, Protocol
from app.providers.models import ProviderResult, ProviderToolCall

class LLMProvider(Protocol):
    name: str
    def generate(self, system_prompt: str, message: str) -> ProviderResult: ...
    def generate_structured(self, system_prompt: str, message: str) -> ProviderResult: ...
    def select_tool(self, message: str, tools: list[dict[str, Any]]) -> ProviderToolCall: ...
    def status(self) -> dict[str, Any]: ...
